### ISSUE TITLE
Managegroup pipeline had to be run multiple times before success 

### ISSUE THREAD

**Issue by KingBain** [Azure/CanadaPubSecALZ#129] opened 2022-01-05 20:54 UTC
**Describe the bug**
Manage group pipeline had to be run multiple times before success. I think there is a race condition where children mgmt groups are being created before parent mgmt groups are available 

**To Reproduce**

- run management group pipeline, receive error running 

`ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Permission to Microsoft.Management/managementGroups on resources of type 'Write' is required on the management group or its ancestors.\",\r\n    \"details\": \"Management Group ID: '/providers/Microsoft.Management/managementGroups/Platform'\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Permission to Microsoft.Management/managementGroups on resources of type 'Write' is required on the management group or its ancestors.\",\r\n    \"details\": \"Management Group ID: '/providers/Microsoft.Management/managementGroups/Platform'\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Permission to Microsoft.Management/managementGroups on resources of type 'Write' is required on the management group or its ancestors.\",\r\n    \"details\": \"Management Group ID: '/providers/Microsoft.Management/managementGroups/Platform'\"\r\n  }\r\n}"}]}}`

- Rerun management group pipeline, error is gone

**Expected behavior**
Run pipeline, pipeline waits for parent mgmt groups to be available before creat child groups 

**Screenshots**

**Comment by KingBain** [comment] 2022-01-05 20:55
The spn the pipeline is using has the appropriate permissions to write to mgmt groups ... it has full permissions .

**Comment by SenthuranSivananthan** [comment] 2022-01-07 00:21
@KingBain I'm not able to reproduce the problem you had.  Can you try again and see if you can reproduce?

My steps:

1. Create a new branch `mgDeploymentCheck`
2. Create a new config file with a new top level management group `test1`

```yaml
variables:
  # Management Groups
  var-parentManagementGroupId: 343ddfdb-bef5-46d9-99cf-ed67d5948783
  var-topLevelManagementGroupName: test1
```

3. Ran the management group DevOps Pipeline
4. Pipeline runs without any errors

Notes:

* No change to pipeline automation
* No change to management group Bicep template
* No change to SPN used by DevOps Pipeline

Results

**Management Groups**
![image](https://user-images.githubusercontent.com/16688027/148470705-f4905a9d-9510-4f56-991b-b419663c6b69.png)

**Pipeline Execution**

Note:  Only 1 pipeline execution using `mgDeploymentCheck` branch

![image](https://user-images.githubusercontent.com/16688027/148470854-627de361-bff0-47ee-84d8-cb82a79fd206.png)

**Comment by SenthuranSivananthan** [comment] 2022-01-21 23:41
Closing this issue since we can't reproduce.  Please reopen if you are still experiencing this error.

**Closed by SenthuranSivananthan** 2022-01-21 23:41 UTC

**Comment by KingBain** [comment] 2022-02-02 21:06
Would like to reopen, went through the testing guidance received a similar error in a different AZ tenant 

Error Message on first deployment
```
Deploying structure.bicep using create operation...
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Permission to Microsoft.Management/managementGroups on resources of type 'Write' is required on the management group or its ancestors.\",\r\n    \"details\": \"Management Group ID: '/providers/Microsoft.Management/managementGroups/LandingZones'\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Permission to Microsoft.Management/managementGroups on resources of type 'Write' is required on the management group or its ancestors.\",\r\n    \"details\": \"Management Group ID: '/providers/Microsoft.Management/managementGroups/LandingZones'\"\r\n  }\r\n}"}]}}
##[error]Caller: 5 /home/vsts/work/_temp/azureclitaskscript1643835322776.sh, LineNo: 1, Command: az deployment mg create --location canadacentral --management-group-id 4652ec81-c92f-4fbe-a5cc-926fd4c5f336 --template-file structure.bicep --parameters parentManagementGroupId=4652ec81-c92f-4fbe-a5cc-926fd4c5f336 topLevelManagementGroupName=Oxygen
##[error]Script failed with exit code: 1
```

What was deployed on first run before pipeline failed 
![image](https://user-images.githubusercontent.com/367922/152237205-bc84804c-cf98-4aa0-a7e8-91f3a9491e7c.png)


Contents od dev,yml file 
variables:

```
    # Management Groups

    var-parentManagementGroupId: 4652ec81-c92f-4fbe-a5cc-926fd4c5f336 #Root ID of DEV tenant
    var-topLevelManagementGroupName: "Oxygen" #top tier of management group model, one lower from root
```

structure.bicep file 
```
// ----------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
// EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
// OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
// ----------------------------------------------------------------------------------

targetScope = 'managementGroup'

@description('Top Level Management Group Name')
@minLength(2)
@maxLength(10)
param topLevelManagementGroupName string

@description('Parent Management Group used to create all management groups, including Top Level Management Group.')
param parentManagementGroupId string

// Telemetry - Azure customer usage attribution
// Reference:  https://docs.microsoft.com/azure/marketplace/azure-partner-customer-usage-attribution
var telemetry = json(loadTextContent('../config/telemetry.json'))
module telemetryCustomerUsageAttribution '../azresources/telemetry/customer-usage-attribution-management-group.bicep' = if (telemetry.customerUsageAttribution.enabled) {
  name: 'pid-${telemetry.customerUsageAttribution.modules.managementGroups}'
}

// Level 1
resource topLevel 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: topLevelManagementGroupName
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: tenantResourceId('Microsoft.Management/managementGroups', parentManagementGroupId)
      }
    }
  }
}

// Level 2
resource platform 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'Platform'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: topLevel.id
      }
    }
  }
}

resource landingzones 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'LandingZones'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: topLevel.id
      }
    }
  }
}

resource sandbox 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'Experimental'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: topLevel.id
      }
    }
  }
}

resource decommissioned 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'Decommissioned'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: topLevel.id
      }
    }
  }
}

resource quarantine 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'Quarantine'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: topLevel.id
      }
    }
  }
}

// Level 3 - Platform
resource platformConnectivity 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'Connectivity'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: platform.id
      }
    }
  }
}

resource platformIdentity 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'Identity'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: platform.id
      }
    }
  }
}

resource platformManagement 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'Management'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: platform.id
      }
    }
  }
}


// Level 3 - Landing Zones

resource nonsensitive 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'NonSensitive'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: landingzones.id
      }
    }
  }
}

resource sensitive 'Microsoft.Management/managementGroups@2020-05-01' = {
  name: 'Sensitive'
  scope: tenant()
  properties: {
    details: {
      parent: {
        id: landingzones.id
      }
    }
  }
}

```

**Comment by SenthuranSivananthan** [comment] 2022-02-02 21:27
@KingBain, this appears to be a platform related problem.  Do you mind opening a support case to understand where the root cause is?

You will need to get the correlation id from the deployment and share w/ Azure Support for tracing the problem.

**Comment by KingBain** [comment] 2022-02-02 21:48
These issues seem related https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/248#issuecomment-1003086938
